### ISSUE TITLE
Exported SQL broken syntax with MySQL 8

### ISSUE THREAD

**Issue by splatterb0y** [mtgjson/mtgsqlive#103]
Import from console prints:
`ERROR 1170 (42000) at line 254: BLOB/TEXT column 'uuid' used in key specification without a key length`

`CREATE TABLE cardForeignData (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	faceName TEXT,
	flavorText TEXT,
	identifiers TEXT,
	language TEXT,
	multiverseId INTEGER,
	name TEXT,
	text TEXT,
	type TEXT,
	uuid TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`

The syntax for the uuid field does not match the syntax of the uuid field in other tables which is:
`uuid VARCHAR(36) NOT NULL`

**Comment by splatterb0y** [comment]
With the most recent updates more fields are now encountering this problem.

**Comment by ZeldaZach** [comment]
Hi there! This project is mostly deprecated now as we've merged the functionality into the main project over at http://github.com/mtgjson/mtgjson -- Hopefully that helps you a bit

You can find new downloads at https://mtgjson.com/api/v5/

**Comment by splatterb0y** [comment]
I'm already using https://mtgjson.com/api/v5/AllPrintings.sql.gz as the remote to download the file. 
Still the problem persists: The syntax is not compatible with MySQL 8.

**Comment by ZeldaZach** [comment]
Can you open a ticket on mtgjson/mtgjson with the issue(s) you're experiencing and we can look into them?
